### ISSUE TITLE
BiocManager not installed?

### ISSUE THREAD

**Issue by Close-your-eyes** [mainciburu/WARPT#1]
Hi to everyone,

I just saw your preprint and wanted to try the method on my sequencing data:

I tried to build the docker image which attempts to install R version 3.5.2 (2018-12-20) -- "Eggshell Igloo", followed by installing selected R packages.
From the error message I believe that BiocManager is not installed:

#7 0.814 > BiocManager::install("ComplexHeatmap")
#7 0.814 Error in loadNamespace(name) : there is no package called ‘BiocManager’
#7 0.814 Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
#7 0.814 Execution halted

Can this be fixed in the docker image?

I am not familiar with docker but I believe this cannot be handled from outside?!

EDIT:
I saw though, that BiocManager is in a vector of packages to install.
But there seems to be a problem:

#7 0.349 > install.packages(c("dplyr", "ggplot2", "RColorBrewer", "cowplot", "reshape2", "gridExtra", "stringr", "mclust", "pheatmap", "BiocManager", "e1071", "pals"))
#7 0.351 Installing packages into ‘/usr/local/lib/R/site-library’
#7 0.351 (as ‘lib’ is unspecified)
#7 0.708 Warning: unable to access index for repository https://cloud.r-project.org/src/contrib:
#7 0.708   cannot open URL 'https://cloud.r-project.org/src/contrib/PACKAGES'
#7 0.717 > 
#7 0.717 > 
#7 0.717 Warning message:
#7 0.717 packages ‘dplyr’, ‘ggplot2’, ‘RColorBrewer’, ‘cowplot’, ‘reshape2’, ‘gridExtra’, ‘stringr’, ‘mclust’, ‘pheatmap’, ‘BiocManager’, ‘e1071’, ‘pals’ are not available (for R version 3.5.2) 
#7 0.766 

Maybe it has to do with the firewall, so I will check that and then close the issue.

Thank you!

**Comment by petervangalen** [comment]
Ok, let us know if that works. I rebuilt the Docker image and, after opening R in the container, verified the following:
```
library(BiocManager)
library(ComplexHeatmap)
```
The input of the software is MiSeq reads: 28 bp for Read 1 (cell barcode + UMI) and 150 bp for Index 1 (TRAV or TRBV). Like the test data.

**Comment by Close-your-eyes** [comment]
So, I think the title of my issue is misleading, I just noticed ...

I believe that BiocManager is the first R package to be called, but the others have not been installed as well (see below).


Here are all the messages from the terminal:
Building 1.2s (8/14)                                                                                                                                                                                                                                                               
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                              0.0s
 => => transferring dockerfile: 211B                                                                                                                                                                                                                                              0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/continuumio/miniconda3:4.10.3                                                                                                                                                                                                          0.5s
 => [internal] load build context                                                                                                                                                                                                                                                 0.0s
 => => transferring context: 1.99kB                                                                                                                                                                                                                                               0.0s
 => [ 1/11] FROM docker.io/continuumio/miniconda3:4.10.3@sha256:a137c7da98c8680467490e15ac3c54e25db77495be1737076b053a6790ad6082                                                                                                                                                  0.0s
 => CACHED [ 2/11] RUN apt-get update && apt-get install -y r-base && apt-get install -y wget                                                                                                                                                                                     0.0s
 => CACHED [ 3/11] RUN conda install python=3.6 && pip install presto==0.6.2 changeo==1.1.0 && conda install -c bioconda -c conda-forge  umi_tools=1.1.2                                                                                                                          0.0s
 => ERROR [ 4/11] RUN R -e 'install.packages(c("dplyr", "ggplot2", "RColorBrewer", "cowplot", "reshape2", "gridExtra", "stringr", "mclust", "pheatmap", "BiocManager", "e1071", "pals"))' && R -e 'BiocManager::install("ComplexHeatmap")'                                        0.6s
------                                                                                                                                                                                                                                                                                 
 > [ 4/11] RUN R -e 'install.packages(c("dplyr", "ggplot2", "RColorBrewer", "cowplot", "reshape2", "gridExtra", "stringr", "mclust", "pheatmap", "BiocManager", "e1071", "pals"))' && R -e 'BiocManager::install("ComplexHeatmap")':                                                   
#7 0.084                                                                                                                                                                                                                                                                               
#7 0.084 R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"                                                                                                                                                                                                                              
#7 0.084 Copyright (C) 2018 The R Foundation for Statistical Computing                                                                                                                                                                                                                 
#7 0.084 Platform: x86_64-pc-linux-gnu (64-bit)                                                                                                                                                                                                                                        
#7 0.084 
#7 0.084 R is free software and comes with ABSOLUTELY NO WARRANTY.
#7 0.084 You are welcome to redistribute it under certain conditions.
#7 0.084 Type 'license()' or 'licence()' for distribution details.
#7 0.084 
#7 0.084 R is a collaborative project with many contributors.
#7 0.084 Type 'contributors()' for more information and
#7 0.084 'citation()' on how to cite R or R packages in publications.
#7 0.084 
#7 0.084 Type 'demo()' for some demos, 'help()' for on-line help, or
#7 0.084 'help.start()' for an HTML browser interface to help.
#7 0.084 Type 'q()' to quit R.
#7 0.084 
#7 0.132 > install.packages(c("dplyr", "ggplot2", "RColorBrewer", "cowplot", "reshape2", "gridExtra", "stringr", "mclust", "pheatmap", "BiocManager", "e1071", "pals"))
#7 0.134 Installing packages into ‘/usr/local/lib/R/site-library’
#7 0.134 (as ‘lib’ is unspecified)
#7 0.481 Warning: unable to access index for repository https://cloud.r-project.org/src/contrib:
#7 0.481   cannot open URL 'https://cloud.r-project.org/src/contrib/PACKAGES'
#7 0.490 Warning message:
#7 0.490 packages ‘dplyr’, ‘ggplot2’, ‘RColorBrewer’, ‘cowplot’, ‘reshape2’, ‘gridExtra’, ‘stringr’, ‘mclust’, ‘pheatmap’, ‘BiocManager’, ‘e1071’, ‘pals’ are not available (for R version 3.5.2) 
#7 0.490 > 
#7 0.490 > 
#7 0.539 
#7 0.539 R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
#7 0.539 Copyright (C) 2018 The R Foundation for Statistical Computing
#7 0.539 Platform: x86_64-pc-linux-gnu (64-bit)
#7 0.539 
#7 0.539 R is free software and comes with ABSOLUTELY NO WARRANTY.
#7 0.539 You are welcome to redistribute it under certain conditions.
#7 0.539 Type 'license()' or 'licence()' for distribution details.
#7 0.539 
#7 0.539 R is a collaborative project with many contributors.
#7 0.539 Type 'contributors()' for more information and
#7 0.539 'citation()' on how to cite R or R packages in publications.
#7 0.539 
#7 0.539 Type 'demo()' for some demos, 'help()' for on-line help, or
#7 0.539 'help.start()' for an HTML browser interface to help.
#7 0.539 Type 'q()' to quit R.
#7 0.539 
#7 0.587 > BiocManager::install("ComplexHeatmap")
#7 0.588 Error in loadNamespace(name) : there is no package called ‘BiocManager’
#7 0.588 Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
#7 0.588 Execution halted
------

I do not think it is a general network problem, because the all the python-related elements could be loaded (CACHED from a previous attempt). So, it is a special thing about the R repository. This cannot be accessed.

Any idea? Problem is, that I cannot access the commands of building the docker.

**Comment by petervangalen** [comment]
I think maybe this is related to the automatic redirection by https://cloud.r-project.org/

I updated Dockerfile to specify `repos = c(CRAN = "https://cran.rstudio.org")` and install an archived version of rjson (a ComplexHeatmap dependency). 

Does that fix the issue for you?

**Comment by Close-your-eyes** [comment]
I talked to my friend of the IT in our institute. I did not understand all the details but it probably has to do with the local firewall. So, in principle this not your fault and rather my business. Unless, this may be a more common problem which also other users are going to face.


The IT friend suggest one of two things:
(i) httr::set_config(config(ssl_verifypeer = 0L))
Run this command in R to switch off checking the SSL certificate.
(ii) http addresses of CRAN instead of https, so that the firewall does not block the traffic.

Maybe this could be an option or an argument to pass, when building the docker?!

**Comment by petervangalen** [comment]
To follow your first suggestion, I think I'd have to install the R package httr first, which may get into a chicken and egg problem. I did update the Dockerfile according to your second suggestion, changing https to http for CRAN.

**Comment by Close-your-eyes** [comment]
Yes that was a fix!
Unfortunately something similar now seems to happen with GitHub in Step 5:
 => [ 4/11] RUN R -e 'install.packages(c("dplyr", "ggplot2", "RColorBrewer", "cowplot", "reshape2", "gridExtra", "stringr", "mclust", "pheatmap", "BiocManager", "e1071", "pals"), repos = c(CRAN = "http://cran.rstudio.org"))' && R -e 'install.packages("htt  215.2s
 => ERROR [ 5/11] RUN wget https://github.com/10XGenomics/cellranger/raw/master/lib/python/cellranger/barcodes/3M-february-2018.txt.gz -P /usr/local/  

Probably again a https problem.

Sorry.

**Comment by petervangalen** [comment]
I replaced all https links in the Dockerfile with http, lmk if that helps

**Comment by Close-your-eyes** [comment]
Unfortunately not,

 => ERROR [ 5/11] RUN wget http://github.com/10XGenomics/cellranger/raw/m  0.3s
------                                                                          
 > [ 5/11] RUN wget http://github.com/10XGenomics/cellranger/raw/master/lib/python/cellranger/barcodes/3M-february-2018.txt.gz -P /usr/local/:                  
#8 0.212 --2022-02-11 08:25:08--  http://github.com/10XGenomics/cellranger/raw/master/lib/python/cellranger/barcodes/3M-february-2018.txt.gz                    
#8 0.212 Resolving github.com (github.com)... 140.82.121.4                      
#8 0.238 Connecting to github.com (github.com)|140.82.121.4|:80... connected.
#8 0.239 HTTP request sent, awaiting response... 301 Moved Permanently
#8 0.270 Location: https://github.com/10XGenomics/cellranger/raw/master/lib/python/cellranger/barcodes/3M-february-2018.txt.gz [following]
#8 0.270 --2022-02-11 08:25:08--  https://github.com/10XGenomics/cellranger/raw/master/lib/python/cellranger/barcodes/3M-february-2018.txt.gz
#8 0.277 Connecting to github.com (github.com)|140.82.121.4|:443... connected.
#8 0.325 ERROR: The certificate of ‘github.com’ is not trusted.
#8 0.325 ERROR: The certificate of ‘github.com’ doesn't have a known issuer.

I am sorry. I think this may be related to the firewall and/or network settings which are be individual for our institute. Since I am not sure if we will benefit from Wat3r I will now close this issue and work on other things. But please, do not feel offended.
