### ISSUE TITLE
Is WAT3R suitable for 5' scRNA-seq with TCR?

### ISSUE THREAD

**Issue by AlicePsyche** [mainciburu/WARPT#2]
Hi WAT3R developers,

Can I use WAT3R for the normal TCR sequencing data from 10x 5' scRNA-seq?  It looks like the only difference is R1 read is 16 CB and 10 UMI, not 12 UMI? 

If not, which package do you recommend for TCR data from 10x 5' scRNA-seq? I am new to this field, would like to hear your expert's opinion ;) Thanks a lot.

Best,
Alice

**Comment by petervangalen** [comment]
I don't know enough about the 5' read structure to say if this will work. If the data was generated with the regular 10x immune profiling kit, my advice is to use Cell Ranger: https://support.10xgenomics.com/single-cell-vdj/software/pipelines/latest/what-is-cell-ranger
