### ISSUE TITLE
Unabale to build container

### ISSUE THREAD

**Issue by mms095** [mainciburu/WARPT#3]
Hi Devs,

Very excited to test out your code but I am running into issues building the docker container. I want to preface that I am completely new to Docker so I may be overlooking something simple when building.

When building the container I initially was unable to install python.

`=> ERROR [ 4/11] RUN conda install python=3.6 && pip install presto=  2.1s`

From the Dockerfile I referenced the image source, continuumio/miniconda3:4.10.3, but found that python 3.6 is not available. Changing the python version to 3.9 allowed me to proceed. Then moving forward it was failing to install umi_tools. 

```
#7 32.16 PackagesNotFoundError: The following packages are not available from current channels:
#7 32.16
#7 32.16   - umi_tools
```

Again I edit the Dockerfile, this time changing the source from anaconda to pypi, and was able to proceed. But now I'm running into an error I can't seem to solve. 

```
#7 41.08     gcc: error: .2-a+fp16+rcpc+dotprod+crypto: No such file or directory
#7 41.08     gcc: error: .2-a+fp16+rcpc+dotprod+crypto: No such file or directory
#7 41.08     gcc: error: unrecognized command line option ‘-n1’; did you mean ‘-n’?
#7 41.08     gcc: error: unrecognized command line option ‘-n1’; did you mean ‘-n’?
#7 41.08     error: command '/usr/bin/gcc' failed with exit code 1
#7 41.08     ----------------------------------------
#7 41.08 ERROR: Command errored out with exit status 1: /opt/conda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-669d2j4s/pysam_e4e6114a58a348479bb4b46e64d38786/setup.py'"'"'; __file__='"'"'/tmp/pip-install-669d2j4s/pysam_e4e6114a58a348479bb4b46e64d38786/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-a7zsn5n8/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.9/pysam Check the logs for full command output.
------
executor failed running [/bin/sh -c conda install python=3.9 && pip install presto==0.6.2 changeo==1.1.0 && pip install umi_tools]: exit code: 1
```

I would greatly appreciate some guidance. I am working in MacOS on Apple M1. Thanks for your time and patience.

**Comment by mainciburu** [comment]
Hi, have you got more info on your initial error? Was it Python that couldn't be installed or any of the modules?

**Comment by mms095** [comment]
Thanks so much for the quick reply. It was initially a failure to install python. Once corrected, its always failing at installation of umi_tools. And if that gets corrected, it gives that large chunk of error code which is where I've been stuck.

Here is the initial error output when the Dockerfile has been unchanged.

```
 > [ 4/11] RUN conda install python=3.6 && pip install presto==0.6.2 changeo==1.1.0 && conda install -c bioconda -c conda-forge  umi_tools=1.1.2:
#7 0.332 Collecting package metadata (current_repodata.json): ...working... done
#7 1.694 Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
#7 1.694 Collecting package metadata (repodata.json): ...working... done
#7 2.591 Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
#7 2.592
#7 2.592 PackagesNotFoundError: The following packages are not available from current channels:
#7 2.592
#7 2.592   - python=3.6
#7 2.592
#7 2.592 Current channels:
#7 2.592
#7 2.592   - https://repo.anaconda.com/pkgs/main/linux-aarch64
#7 2.592   - https://repo.anaconda.com/pkgs/main/noarch
#7 2.592   - https://repo.anaconda.com/pkgs/r/linux-aarch64
#7 2.592   - https://repo.anaconda.com/pkgs/r/noarch
#7 2.592
#7 2.592 To search for alternate channels that may provide the conda package you're
#7 2.592 looking for, navigate to
#7 2.592
#7 2.592     https://anaconda.org
#7 2.592
#7 2.592 and use the search bar at the top of the page.
#7 2.592
#7 2.592
------
executor failed running [/bin/sh -c conda install python=3.6 && pip install presto==0.6.2 changeo==1.1.0 && conda install -c bioconda -c conda-forge  umi_tools=1.1.2]: exit code: 1
```

**Comment by petervangalen** [comment]
Hi,
I was able to reproduce the error of being unable to install umi_tools when using python=3.9
But with the original Python 3.6 the `docker build` command does not give errors for me.
I will investigate why Python 3.6 was not available for you.
Peter

**Comment by petervangalen** [comment]
Are you using a Apple M1 Max computer by any chance?

**Comment by mms095** [comment]
Hi there. My computer is using an M1 Pro processor.

From: Peter van Galen ***@***.***>
Date: Monday, February 21, 2022 at 9:14 AM
To: mainciburu/WAT3R ***@***.***>
Cc: Medina-Serpas, Miguel A. ***@***.***>, Author ***@***.***>
Subject: Re: [mainciburu/WAT3R] Unabale to build container (Issue #3)
[External Email]

Are you using a Apple M1 Max computer by any chance?

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mainciburu_WAT3R_issues_3-23issuecomment-2D1046924000&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=MtKkbYWVoRDJfchtr8QS09qONktLZiTa77_bZw64sIA&m=wR2HX-40MuzJXo7mCqTctFHQuQTX8SrOecz56XDSYoI46kpAtOGngqBv_2s8kC2J&s=zjKSwjQZBfQNf2uGnARFUhnXiPwLVMnsJOFpIoJ1EtQ&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AXSBYQZHJ3FT75UX6N3IE73U4JCERANCNFSM5N25OAUA&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=MtKkbYWVoRDJfchtr8QS09qONktLZiTa77_bZw64sIA&m=wR2HX-40MuzJXo7mCqTctFHQuQTX8SrOecz56XDSYoI46kpAtOGngqBv_2s8kC2J&s=sxzhqmcEAgFHbnrQk62Wnf4yWKy48pSREolaC8rbv8U&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=MtKkbYWVoRDJfchtr8QS09qONktLZiTa77_bZw64sIA&m=wR2HX-40MuzJXo7mCqTctFHQuQTX8SrOecz56XDSYoI46kpAtOGngqBv_2s8kC2J&s=5PWW57jHZGnmXXUFPvVMmavPr267mqbGIcjvkyIMh4w&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=MtKkbYWVoRDJfchtr8QS09qONktLZiTa77_bZw64sIA&m=wR2HX-40MuzJXo7mCqTctFHQuQTX8SrOecz56XDSYoI46kpAtOGngqBv_2s8kC2J&s=tLDqkXGbVRDN3cp9tEf05NiSFijyh7ygpV-J6YtL28k&e=>.

**Comment by petervangalen** [comment]
Hi,

Thanks for your patience. I don't have a solution but found that the errors occur on Mac with M1 processor (M1 Pro and M1 Max). I was able to successfully build the image using [this line](https://gonzalo123.com/2021/08/02/handling-m1-problems-in-python-local-development-using-docker/):
```docker buildx build --platform linux/amd64 -t mainciburu/wat3r .```
(you may  need to add the option `--no-cache` and/or [install rosetta](https://docs.docker.com/desktop/mac/apple-silicon/) using `softwareupdate --install-rosetta`)

When running wat3r, I am now getting another error when the `igblastn` is being executed. This is the error:
```qemu:handle_cpu_signal received signal outside vCPU context @ pc=0x451f76```

I have not been able to get around this. The quickest solution would be to run WAT3R on a cluster or Terra.bio, but I will continue to look into this.
