### ISSUE TITLE
Unable to install WAT3R

### ISSUE THREAD

**Issue by raman91** [mainciburu/WARPT#4]
Hi, 

I am installing WAT3R but i get an error on running docker build -t mainciburu/wat3r . :

gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

May i know how i can solve this issue?

Thanks

**Comment by mainciburu** [comment]
Hello, 
Could you give some more detail on the specific step at which this error occurs? There are two decompression steps that could be throwing this error.

**Comment by raman91** [comment]
Hi,

I get this error when building the docker image :
docker build -t mainciburu/wat3r .

**Comment by mainciburu** [comment]
Hi! I understand that. 
The thing is, when you build the docker image you can usually see the process is divided in a set of steps. They are indicated as [1/14], [2/14], ..., [14/14]. 
It would be useful to know at which one the error occurred.

**Comment by raman91** [comment]
Hi, sorry for the late reply. 
I am getting the error in [11/14] step as below :

--2022-03-29 05:37:33--  http://bitbucket.org/kleinstein/immcantation/raw/9e5f6fb95edda9901238abc28da8a29948f9de82/scripts/fetch_igblastdb.sh
Resolving bitbucket.org (bitbucket.org)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘bitbucket.org’

**Comment by petervangalen** [comment]
Perhaps the link is blocked in your environment. Can you check by trying to download the file as follows?
`wget http://bitbucket.org/kleinstein/immcantation/raw/9e5f6fb95edda9901238abc28da8a29948f9de82/scripts/fetch_igblastdb.sh .`

**Comment by petervangalen** [comment]
I am closing this issue, if issues persist please comment to re-open.
