### ISSUE TITLE
Speedup QC step in R

### ISSUE THREAD

**Issue by scfurl** [mainciburu/WARPT#5]
Hi @petervangalen,

First off, thanks for building this pipeline!!  I wonder if you might consider a few changes to the _QCplots_clustering.r_ R script.  I have been running wat3r on a sequencing run with ~80 million reads and I have been waiting 5 or 6 days now for the QC step to finish.  While I have been waiting, I processed the data using a modified script with a few key changes and it ran in an hour or so.

I used data.tables instead of data.frames and used fread and fwrite commands to read and write to the disk.  Happy to do a push request if you like.

Thanks!

**Comment by petervangalen** [comment]
That sounds great! We have never used >15 million reads (most samples we analyze are on the MiSeq, 28 bp for Read1 + 150 bp for "Index 1"). Are you also using TCR-enriched data of a similar structure? Sure, push request would be great! @mainciburu

**Comment by scfurl** [comment]
Thanks @petervangalen.  I just submitted a pull request...  We ran our data on a NextSeq P1 300 flow cell with 28bp for Read1 and 299bp for "Index 1".  We seemed to lose a lot of reads at the clustering step with only ~9% that met thresholds.  Does this fit with your expectations? 
<img width="760" alt="image" src="https://user-images.githubusercontent.com/16267955/162481980-ee7d45cb-1442-4912-843f-ed2449bb81d5.png">

**Comment by petervangalen** [comment]
I attached our PBMC sample. From the main page: x shows the proportion of reads assigned to the most highly ranked TCR cluster, y shows the log ratio of the reads in the first over the second-ranked TCR cluster (in that cell). The color is the number of reads per CB-UMI. You can adjust -p and -r in `downstream` to use less stringent thresholds. This would discard less reads and potentially reduce confidence that you are calling the right TCR. @mainciburu will have more insight.
[QCplot_clusters.pdf](https://github.com/mainciburu/WAT3R/files/8454562/QCplot_clusters.pdf)
