### ISSUE TITLE
Sample Index Consideration?

### ISSUE THREAD

**Issue by WesAbplanalp** [mainciburu/WARPT#6]
First, thanks for the nice pipeline!!! The protocol considers barcode/UMI files and the cDNA.  Is it possible to also have the sample index considered to more quickly split responses of cells which were sequenced together? Any insights are appreciated.

**Comment by petervangalen** [comment]
This is currently not possible. I recommend demultiplexing with bcl2fastq to generate separate fastqs for every sample. Out of curiosity and if we would consider this feature for an update: is the index barcode in a separate fastq?
