### ISSUE TITLE
Issue after starting container

### ISSUE THREAD

**Issue by zthoms** [mainciburu/WARPT#8]
I was able to build the docker image and then after starting the container, when I run:
"wat3r -h" 

I get the following output: 
![wat3r_error](https://user-images.githubusercontent.com/67016562/168886864-db1d171b-8445-46ca-869f-bc8aeb3d646c.PNG)

Any ideas?

**Comment by petervangalen** [comment]
I have not seen this issue before.
1- What computer / OS are you using?
2- From within the container, what is the result of these commands?
`cat /etc/os-release`
`ls /usr/local/bin/`

**Comment by zthoms** [comment]
This is on windows 10 - also new to docker so might be user error here when initially starting the container. 

But from within the container, this is the output:
![wat3r_trblsht](https://user-images.githubusercontent.com/67016562/169094290-f9e816fb-aeae-4377-b2af-5dcac8ca111e.PNG)
