### ISSUE TITLE
Error in downstream segment

### ISSUE THREAD

**Issue by zthoms** [mainciburu/WARPT#9]
Running into an issue in the downstream portion of the pipeline. The "wat3r" portion seems to run fine with no errors. I've attached a screenshot of the terminal as well as the log files for both "wat3r" and "downstream". Overall the "downstream" portion does output the two result tables, but only exports the db_histograms.pdf plot and not the ReadPercentage_FilteringSteps.pdf plot. 

[mysample_downstream.log](https://github.com/mainciburu/WAT3R/files/8920871/mysample_downstream.log)
[wat3r.log](https://github.com/mainciburu/WAT3R/files/8920872/wat3r.log)
![downstream_error](https://user-images.githubusercontent.com/67016562/174123860-a251a480-3f2a-4044-93ee-4de6d79ccced.PNG)

**Comment by mainciburu** [comment]
Hi, 
It looks like you didn't add a file with cell annotations when running `downstream`, using the option `-a /path/to/annotations.txt`. You need it in order to get the rest of the plots. Everything else looks good!

**Comment by zthoms** [comment]
Thanks! I tried it again and passed in the -a option with an annotation file. Looks like the rest of the plots are generated, with the exception of the ReadPercentage_FilteringSteps.pdf plot. This one is still missing but realistically is probably the least important.

**Comment by petervangalen** [comment]
The read percentages are also reported in this file: downstream/wat3rMetrics_downstream.txt
I'm going to close this ticket since it has been inactive for a few months but please re-open if you have more questions.
